# Generated by Django 4.2.5 on 2023-11-14 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, verbose_name="graph's name")),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, verbose_name="node's name")),
                ('graph_id', models.ForeignKey(db_column='graph_id', on_delete=django.db.models.deletion.CASCADE, to='algorythm.graph')),
                ('parents', models.ManyToManyField(related_name='children', to='algorythm.node')),
            ],
        ),
    ]
