# Generated by Django 4.2.5 on 2023-11-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorythm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graph',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='node',
            old_name='graph_id',
            new_name='graph',
        ),
        migrations.AlterField(
            model_name='graph',
            name='name',
            field=models.CharField(max_length=80, verbose_name="graph's =  name"),
        ),
    ]
