# Generated by Django 4.2.5 on 2023-12-22 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algorythm', '0002_rename_user_id_graph_user_rename_graph_id_node_graph_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='graph',
            options={'ordering': ['id']},
        ),
    ]
