# Generated by Django 4.2.5 on 2023-12-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorythm', '0004_alter_graph_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graph',
            old_name='user',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='graph',
            name='name',
            field=models.CharField(max_length=80, verbose_name="graph's name"),
        ),
    ]
