# Generated by Django 4.2.5 on 2023-12-23 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('algorythm', '0005_rename_user_graph_owner_alter_graph_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='graph',
            field=models.ForeignKey(db_column='graph_id', on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='algorythm.graph'),
        ),
    ]
