# Generated by Django 4.2.5 on 2023-10-02 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, verbose_name="node's name")),
            ],
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('predecessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heads', to='algorythm.node')),
                ('sucessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tails', to='algorythm.node')),
            ],
        ),
    ]
