# Generated by Django 4.2.5 on 2023-10-09 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorythm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='parents',
            field=models.ManyToManyField(related_name='children', to='algorythm.node'),
        ),
        migrations.DeleteModel(
            name='Edge',
        ),
    ]
